### ISSUE TITLE
请问如果是并发问题怎么处理呢？

### ISSUE THREAD

**Issue by allovine** [poolbang/queue#1]
![image](https://user-images.githubusercontent.com/15407088/47056615-d1ad8900-d1ef-11e8-9b0a-f0c04b33395f.png)
在任务执行时，应该是同步执行的，如果任务多，或者单个任务执行时间长，是不是就不能保证并发效率了？

**Comment by webphplove** [comment]
默认是开启协程模式的，而且还是单开一个进程来处理队列，对并发影响不大

**Comment by allovine** [comment]
谢谢回复。
对swoole和swoft的协程理解的还不清楚，不知道都什么时候会采取协程的模式执行。

我看代码里面，在process代码里启动的touchTimer来扫描队列，并且在扫描到时候进行的时间判断和拉起job处理，在touchTimer内部，看不到有协程的的模式，比如拉起job采用特殊的函数拉起一个协程来出来job。

我用代码测试下并发再回复吧。

**Comment by allovine** [comment]
我在 job 的 perform 函数里面增加一个sleep观察下效果，代码如下：
protected function perform()
    {
        echo  date('Y-m-d H:i:s').'   JobId: ' . $this->id . " begin". PHP_EOL;
        $this->demoRedis->set("logic_".rand(1,100),"is me");
        sleep(2);
        echo  date('Y-m-d H:i:s').'   JobId: ' . $this->id . " end". PHP_EOL;
    }
然后往queue里面放的时候是这么放的：
for($j=0;$j<10;$j++){
        DelayQueue::enqueue('topic', \App\Models\Logic\QueueLogic::class, 10, 3, ['id' => 8008]);
}
运行起来之后的效果如图：
![image](https://user-images.githubusercontent.com/15407088/47082641-d77f8a80-d240-11e8-988c-7dabb4b932d2.png)
我想达到一个效果就是不要因为单个job的执行时间长，导致队列里面的任务没有及时被处理，从日志上看达不到并发的效果。而且日志有点看不懂，希望能请教下，扫描进程不知道是怎么执行任务的，有些任务是只有begin看不到end，有些只有end，就是begin和end不是成对出现，一个job可能会有多个begin。这些日志情况是什么原因呢？

另外在 touchTimer 里面拉起任务的时候，能够启动一个新进程执行任务吗？是不是只有投递任务这种方式来处理？

**Comment by webphplove** [comment]
确实有任务重复执行，谢谢issues，现已经修复了，请重新下载测试一下
1，协程模式下，不要使用php的sleep函数，要使用co::sleep(),这样不会重复执行。
2，touchTimer是swoft启动时开启的一个进程来执行任务，执行时不会产生新的进程。是用go()来处理投递任务的

**Comment by allovine** [comment]
更新测试了下，有两个问题：
![image](https://user-images.githubusercontent.com/15407088/47122604-139b0580-d2aa-11e8-9321-2d0ed587c866.png)


1，扫描队列不能做到一次性扫描后拉起所有需要执行的job，只能每秒执行一个
2，在job里面用 inject 方式的 redis 失败了，在 touchTimer 里面去掉 go 函数拉起的方式执行 run ，同样也是 redis 使用不了，job 里面的代码如下：
class QueueLogic extends JobHandler
{

    /**
     * 别名注入
     *
     * @Inject("demoRedis")
     *
     * @var demoRedis
     */
    private $demoRedis;
    
    protected function perform()
    {
        echo  date('Y-m-d H:i:s').'   JobId: ' . $this->id . " begin". PHP_EOL;
        $this->demoRedis->set("logic_".rand(1,100),"is me");
        co::sleep(2);
        echo  date('Y-m-d H:i:s').'   JobId: ' . $this->id . " end". PHP_EOL;
    }
}



我看下源代码调试下，您要是能快速定位就更好了

**Comment by allovine** [comment]
![image](https://user-images.githubusercontent.com/15407088/47123159-9c1aa580-d2ac-11e8-8a31-b12dd2967453.png)


这样修改后执行效果如下：
![image](https://user-images.githubusercontent.com/15407088/47123167-a8066780-d2ac-11e8-8cbe-079e13faadd6.png)


挺好的，我再加入redis的set和get，看看在sleep的时候相互之间传递数据会怎么样

**Comment by allovine** [comment]
还有个问题，正如上面截图，下半部分，再job里面sleep之后，使用 $this->id 输出，居然都是最后一个job的id，如果在job开始用一个变量存储下来 $this->id 就没这个问题，没时间测试了。


能否请您修改下 run 里面go执行的内容，把直接 $queueClass = new $jobInfo['class'](); 这样还修改回  $queueClass = App::getBean($jobInfo['class']);  ，要不在job里面没法使用 inject 的redis。

**Comment by webphplove** [comment]
@Bean 的默认方式是 Scope::SINGLETON(单例模式)，不会产生新的class；在执行job时，都是在一个类内完成，所以co::sleep后，会重复执行最后的JobId。
修改方式如下:
1，修改@Bean的scope为Scope::PROTOTYPE(每次创建)，这样每次都在不同的类执行job，可以避免重复Job。
2，用 new 一个class的方式，也是每次创建，这样也可以避免重复Job执行

**Comment by webphplove** [comment]
我们来运行下面的例子：
```
class Singleton {
    static private $instance;
    
    static public function getInstance()
    {
        if(!self::$instance instanceof self){
            self::$instance = new self();
        }
        return self::$instance;
    }

    private $id;

    public function setId($id){
        $this->id = $id;
    }

    public function run()
    {
        echo $this->id;
        \co::sleep(2);
        echo $this->id;
    }

}

for ($i=0; $i < 10; $i++){
    go(function() use($i){
        $class = Singleton::getInstance();
        $class->setId($i);
        $class->run();
    });
}
```
结果:
`01234567899999999999`
所以出现了，最后的Job会重复执行

**Comment by allovine** [comment]
哦，谢谢讲解，对框架了解不多，见笑了。

那用两种方式来解决redis的注入引用问题，一个是run里面使用getBean，同时把bean设置成 Scope::PROTOTYPE。另一个就是不用注入的方式引用，直接创建redis连接。

是吗？

另外，您要修改 run 里面采用 getBean 方式吗？还是依然像现在这样 class 的方式？或者开放出去一个接口，enque的时候，增加一个执行方式的入参？

**Comment by allovine** [comment]
> 我们来运行下面的例子：
> 
> ```
> class Singleton {
>     static private $instance;
>     
>     static public function getInstance()
>     {
>         if(!self::$instance instanceof self){
>             self::$instance = new self();
>         }
>         return self::$instance;
>     }
> 
>     private $id;
> 
>     public function setId($id){
>         $this->id = $id;
>     }
> 
>     public function run()
>     {
>         echo $this->id;
>         \co::sleep(2);
>         echo $this->id;
>     }
> 
> }
> 
> for ($i=0; $i < 10; $i++){
>     go(function() use($i){
>         $class = Singleton::getInstance();
>         $class->setId($i);
>         $class->run();
>     });
> }
> ```
> 结果:
> `01234567899999999999`
> 所以出现了，最后的Job会重复执行

谢谢讲解，这个理解的，您之前说到bean的scope的时候，我大概理解了。

**Comment by webphplove** [comment]
> 哦，谢谢讲解，对框架了解不多，见笑了。
> 
> 那用两种方式来解决redis的注入引用问题，一个是run里面使用getBean，同时把bean设置成 Scope::PROTOTYPE。另一个就是不用注入的方式引用，直接创建redis连接。
> 
> 是吗？
> 
> 另外，您要修改 run 里面采用 getBean 方式吗？还是依然像现在这样 class 的方式？或者开放出去一个接口，enque的时候，增加一个执行方式的入参？

1，并不会创建新的redis连接
2，暂时用new的方式，如果用getBean方式，只是修改执行QueueLogic的scope的类型就行了，enqueue不会有所改变

**Comment by allovine** [comment]
> > 哦，谢谢讲解，对框架了解不多，见笑了。
> > 那用两种方式来解决redis的注入引用问题，一个是run里面使用getBean，同时把bean设置成 Scope::PROTOTYPE。另一个就是不用注入的方式引用，直接创建redis连接。
> > 是吗？
> > 另外，您要修改 run 里面采用 getBean 方式吗？还是依然像现在这样 class 的方式？或者开放出去一个接口，enque的时候，增加一个执行方式的入参？
> 
> 1，并不会创建新的redis连接
> 2，暂时用new的方式，如果用getBean方式，只是修改执行QueueLogic的scope的类型就行了，enqueue不会有所改变

就是用 new 的方式，我就需要在job里面直接创建redis连接，而不能用inject的方式，对吧

**Comment by webphplove** [comment]
可以，推荐用inject注入方式

**Comment by allovine** [comment]
> 可以，推荐用inject注入方式

如果用 new 的方式，在 job 里面用 inject 的方式，会报错的，可能我没说清楚，我跟您一直说的就是这个问题，我把日志发给您

![image](https://user-images.githubusercontent.com/15407088/47126496-6df09200-d2bb-11e8-99cf-17dd82ec418c.png)


job 的代码：
![image](https://user-images.githubusercontent.com/15407088/47126516-86f94300-d2bb-11e8-9b21-8e1e816d5842.png)

**Comment by webphplove** [comment]
```
namespace App\Models\Logic;

use Queue\JobHandler;
use Swoft\Bean\Annotation\Bean;
use Swoft\Bean\Annotation\Inject;
use Swoft\Bean\Annotation\Scope;
use Swoft\Redis\Redis;


/**
 * @Bean(scope=Scope::PROTOTYPE)
 * Class QueueLogic
 * @package App\Models\Logic
 */
class QueueLogic extends JobHandler
{

    /**
     * @Inject()
     * @var Redis
     */
    private $redis;

    protected function perform()
    {
        echo date('Y-m-d H:i:s').' JobId: ' . $this->id . " begin". PHP_EOL;
        $score = rand(1,2);
        if ($score == 1){
            $this->redis->zAdd('test_z', $score, $this->id);
            $this->redis->zRange('test_z', 0, -1);
            \co::sleep($score);
        }else{
            \co::sleep($score);
            $this->redis->zAdd('test_z', $score, $this->id);
            $this->redis->zRange('test_z', 0, -1);
        }
        echo date('Y-m-d H:i:s').' JobId: ' . $this->id . " end". PHP_EOL;
    }
}
```
我这个测试，没有出现你这样的情况, 是不是你的redis连接有问题
`ps:这里用Scope::PROTOTYPE,我把包里面的方式改为getBean了`

**Comment by allovine** [comment]
> ```
> namespace App\Models\Logic;
> 
> use Queue\JobHandler;
> use Swoft\Bean\Annotation\Bean;
> use Swoft\Bean\Annotation\Inject;
> use Swoft\Bean\Annotation\Scope;
> use Swoft\Redis\Redis;
> 
> 
> /**
>  * @Bean(scope=Scope::PROTOTYPE)
>  * Class QueueLogic
>  * @package App\Models\Logic
>  */
> class QueueLogic extends JobHandler
> {
> 
>     /**
>      * @Inject()
>      * @var Redis
>      */
>     private $redis;
> 
>     protected function perform()
>     {
>         echo date('Y-m-d H:i:s').' JobId: ' . $this->id . " begin". PHP_EOL;
>         $score = rand(1,2);
>         if ($score == 1){
>             $this->redis->zAdd('test_z', $score, $this->id);
>             $this->redis->zRange('test_z', 0, -1);
>             \co::sleep($score);
>         }else{
>             \co::sleep($score);
>             $this->redis->zAdd('test_z', $score, $this->id);
>             $this->redis->zRange('test_z', 0, -1);
>         }
>         echo date('Y-m-d H:i:s').' JobId: ' . $this->id . " end". PHP_EOL;
>     }
> }
> ```
> 我这个测试，没有出现你这样的情况, 是不是你的redis连接有问题
> `ps:这里用Scope::PROTOTYPE,我把包里面的方式改为getBean了`

感谢！
我用Mac电脑测试的，之前也有奇怪的问题，反馈到swoft那里，也是mac总会有奇怪的问题，可能这个问题也是mac的原因吧。
